namespace Commons.Enums
{
	public enum MessageCode
	{
		// User

		USER_SUCCESSFULLY_CREATED,
		USER_NOT_CREATED,
		USER_FOUND,
		USER_NOT_FOUND,
		USER_EMAIL_ALREADY_EXISTS,
		USERS_FOUND,
		USERS_NOT_FOUND,
		USER_SUCCESSFULLY_UPDATED,
		USER_NOT_UPDATED,
		USER_SUCCESSFULLY_BLOCKED,
		USER_BLOCKED,
		USER_NOT_BLOCKED,
		USER_ALREADY_BLOCKED,
		USER_SUCCESSFULLY_UNBLOCKED,
		USER_NOT_UNBLOCKED,
		USER_SUCCESSFULLY_DELETED,
		USER_NOT_DELETED,

		//AUTH

		AUTH_USER_NOT_FOUND,
		AUTH_TOKEN_NOT_GENERATED,
		AUTH_SUCCESSFULLY,
		AUTH_REFRESH_TOKEN_NOT_FOUND,
		AUTH_REFRESH_TOKEN_USER_INVALID,
		AUTH_REFRESH_TOKEN_NOT_REFRESHTED,
		AUTH_REFRESH_TOKEN_REFRESHTED,
		AUTH_ACCESS_IS_VALID,
		AUTH_ACCESS_NOT_IS_VALID,
		AUTH_ACCESS_NOT_FOUND,

		// Erros comuns da api

		API_INTERNAL_ERROR,
		API_ORIGIN_IN_CONVERTER_IS_NULL
	}

}